title: Carlos De Labra# your name (or website title) here
logo: "/images/perfil.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Scientist Jr. portfolio for presenting the following projects 
  <br><br>
  Portafolio de un Cientifico de Datos Jr. para presentar sus proyectos realizados
  <br><br>
  <a href="https://www.linkedin.com/in/carlosdelabrarivera/"> View my Linkedin Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
